# aegis_v2/language/parser.py

from lark import Lark, Transformer, v_args
from typing import List

# --- Abstract Syntax Tree (AST) Node Definitions ---
# These classes represent the hierarchical structure of a parsed TL-SAFE formula.
# Having a clean AST is the first step to compiling the spec into other formats.

class ASTNode:
    """Base class for all AST nodes."""
    pass

class Predicate(ASTNode):
    def __init__(self, name: str, terms: List[str]):
        self.name = name
        self.terms = terms
    def __repr__(self) -> str:
        return f"Predicate({self.name}, {self.terms})"

class Not(ASTNode):
    def __init__(self, formula: ASTNode):
        self.formula = formula
    def __repr__(self) -> str:
        return f"Not({self.formula})"

class And(ASTNode):
    def __init__(self, left: ASTNode, right: ASTNode):
        self.left = left
        self.right = right
    def __repr__(self) -> str:
        return f"And({self.left}, {self.right})"

class Implies(ASTNode):
    def __init__(self, left: ASTNode, right: ASTNode):
        self.left = left
        self.right = right
    def __repr__(self) -> str:
        return f"Implies({self.left}, {self.right})"

class Globally(ASTNode):
    def __init__(self, formula: ASTNode):
        self.formula = formula
    def __repr__(self) -> str:
        return f"Globally({self.formula})"

# --- TL-SAFE Grammar ---
# This grammar is defined using Lark's EBNF syntax. It specifies the rules for
# parsing TL-SAFE strings. It handles operator precedence (¬ binds tightest, then ∧, then →)
# and right-associativity for implication.

tl_safe_grammar = r"""
    ?formula: implies

    ?implies: and_expr ( "→" implies )?
    ?and_expr: negation ( "∧" and_expr )?
    ?negation: "¬" atom -> not_op
              | atom

    ?atom: CNAME "(" [term ("," term)*] ")" -> predicate
         | "G" "(" formula ")"             -> globally
         | "(" formula ")"

    ?term: CNAME      -> var
         | ESCAPED_STRING -> string

    %import common.CNAME
    %import common.ESCAPED_STRING
    %import common.WS
    %ignore WS
"""

# --- AST Transformer ---
# This class walks the parse tree generated by Lark and transforms it into our
# custom AST nodes defined above. Each method corresponds to a rule in the grammar.

@v_args(inline=True)
class ASTBuilder(Transformer):
    def string(self, s):
        return s[1:-1]  # Remove the surrounding quotes

    def var(self, v):
        return str(v)

    def term(self, t):
        return t

    def predicate(self, name, *terms):
        return Predicate(str(name), list(terms))

    def not_op(self, formula):
        return Not(formula)

    def and_expr(self, left, right=None):
        return And(left, right) if right else left

    def implies(self, left, right=None):
        return Implies(left, right) if right else left

    def globally(self, formula):
        return Globally(formula)

# --- Main Parser Class ---

class TlSafeParser:
    """A parser for the TL-SAFE specification language."""
    def __init__(self):
        self.parser = Lark(
            tl_safe_grammar,
            start='formula',
            parser='lalr',
            transformer=ASTBuilder()
        )

    def parse(self, text: str) -> ASTNode:
        """
        Parses a TL-SAFE specification string into an AST.

        Args:
            text: The string containing the TL-SAFE formula.

        Returns:
            The root node of the Abstract Syntax Tree.

        Raises:
            lark.exceptions.LarkError: If the text is not a valid formula
                                       according to the grammar.
        """
        return self.parser.parse(text)
